SportingGoodsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportingGoodsStore.Models;

namespace SportingGoodsStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

SportingGoodsStore/Components/NavigationMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportingGoodsStore.EF;

namespace SportingGoodsStore.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly IStoreRepository _repository;

        public NavigationMenuViewComponent(IStoreRepository repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_repository.Products
                .Select(x => x.Category)
                .Distinct().OrderBy(x => x));
        }
        
    }
}

SportingGoodsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float: right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductId" asp-page="/Cart" method="post">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float:right">Add to cart</button>
        </span>
    </form>
</div>

SportingGoodsStore/Views/Shared/_Layout.cshtml
<html>
    <head>
        <meta name="viewport" content="width=device-width"/>
        <title>SportingGoodsStore</title>
        <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
        <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    </head>
    <body>
        <div class="bg-dark text-white p-2">
            <div class="container-fluid">
                <div class="row">
                    <div class="col navbar-brand">SPORTING GOODS STORE</div>
                    <div class="col-6 text-right">
                        <vc:cart-summary />
                    </div>
                </div>
            </div>
        </div>
        <div class="row m-1 p-1">
            <div id="categories" class="col-3">
                <vc:navigation-menu />
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </body>
</html>